language: python
python:
  - "3.6"
  - "3.8"
  # PyPy versions
  #  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  #  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install .
# command to run tests
script: PYTHONPATH=neoload;tests/helpers pytest

