language: python
addons:
  sonarcloud:
    organization: "neotys-rd" # the key of the org you chose at step #3
    token:
      secure: "UuMYHkiK1RvfHcBMMwFzgrAlu+Uyuto2q8RWq4KiWBDl7iAk9HfyJ1M8zFpHVz5lMrMcdQ8XoaOIwaSnKkS62lGocY9xpLPP4ZmpKTbNOIy87pJ0fuTX36ubcPKQZtdyVhR5rf6gewL4Oy0q20oTm768knudZJnL5SpDfMfQDnSpnysZt+QgT5VxqvVknIakNdwmnaBBM0EwHIFETCltSacR5SUnCZZMrId70rQ2TuBtx8x27L8Fo5U/tZ71R053FYIKPaDLARem6AhFeZjxT1GbeInrcfMiebFdwm/DliRfQmyH585v/JlPlC8Wcywpb6Iy2E47sD6vwE9650tj2+6xQH9Nft8w8VOvxb8JQFyujYkWlSID68nMRnADq3tdNzfVrd+Wk5GvB2gPYx9nqDW77RAD/18SFNI0LXCfg4H77PorACoIb0HoL0JG9GciAQVinj8yzLpE+jcFuWmVp/gni9f63aHD2mk/Zfh+aB8VWHIYy3+JiHzC01UfceBLQKifdlGvqP49ZR1gp46DmyjXpUvHe1JQaOJ/ezK8vw91MtaMaYEhBISRA7JDfBNSQ49BUTDe6p9fjxvluI3DmXoe5bWiGIHOTKvbEQMCUflx2KpjxV953sRblasjwNDsf0tFxdzhwJkBluIASurxUWeQ91jkuqrwCtU2gfAuTRU="

python:
  - "3.6"
  - "3.8"
  # PyPy versions
  #  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  #  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - PYTHONPATH=neoload pytest
  - sonar-scanner
