trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: neoloadApiUrl
  type: string
  default: 'https://neoload-api.saas.neotys.com/'
- name: neoloadToken
  type: string
  default: '89cab48f24a22b8de0f15dbf0537ca59d0975a9becb27d1b'
- name: zoneId
  type: string
  default: 'defaultzone'

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test from Azure Devops
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version
  - task: Bash@3
    displayName: Configure the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload login --url ${{parameters.neoloadApiUrl}} ${{parameters.neoloadToken}}
        
        neoload status
        neoload workspaces --help
             
        neoload workspaces ls
        neoload workspaces use "01_AyaNeoPerf_GUI" 
        neoload test-settings --help
        
        neoload test-settings ls
        neoload test-settings use vptest3
        
        
  - task: Bash@3
    displayName: Run the NeoLoad test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload run \
                       --web-vu 5 \
                       --as-code default.yaml,slas/uat.yaml \
                       --name "Azure pipeline performance regression task $(Build.BuildNumber)" \
                       --external-url "$(Build.BuildUri)" \
                       --external-url-label "Azure CI build $(Build.BuildNumber)" \
                       --description "Azure result description" \
                       "MySpaceMay4"
  - task: Bash@3
    displayName: Get the junit SLA report
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
       neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
