image: "python:3.8"

stages:
 - test

loadtest:
 stage: test
 allow_failure: false
 script:
   - |
    git clone https://github.com/Neotys-Labs/neoload-cli.git && cd neoload-cli
    pip install -q neoload
        neoload login $(nlw_secret_token) \
                test-settings create MyOpenshiftTest --zone pimnV --scenario sanityScenario \
                upload tests/neoload_projects/example_1/everything.yaml \
                run \
                    --as-code tests/neoload_projects/example_1/everything.yaml,tests/neoload_projects/example_1/slas/uat.yaml
                    --junitsla neoload-slas.xml
