# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Docker Commands

on:
  push:
    branches: [ 'TestDockerInGithubActions' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6'] #, '3.8']
    env:
      zoneId: xWbV4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Host docker agent to DinD
      run: |
        #pip install docker
        docker ps
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Docker Up/Down
      run: |
        neoload login --url ${{ secrets.NLWEB_API_URL }} --workspace CLI ${{ secrets.NLWEB_TOKEN }}
        neoload config set docker.controller.image=public.ecr.aws/neotys/neoload-controller:7.7.0
        neoload config set docker.lg.image=public.ecr.aws/neotys/neoload-loadgenerator:7.7.0
        neoload config set docker.zone=${{ env.zoneId }}
        neoload docker status
        neoload docker up
        neoload docker down
    - name: Test with pytest
      run: |
        PYTHONPATH="neoload" COVERAGE_FILE=.coverage.unit coverage3 run -m pytest
        PYTHONPATH="neoload" COVERAGE_FILE=.coverage.live coverage3 run -m pytest -v -x -m "makelivecalls" --makelivecalls --token ${{ secrets.NLWEB_TOKEN }} --url ${{ secrets.NLWEB_API_URL }} --workspace CLI
        coverage3 combine
        coverage3 xml
    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Zip Test Folder on failure
      if: failure()
      run: zip -r tests.zip tests/
    - name: Upload Test Folder on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-folder ${{ matrix.node-version }}
        path: tests.zip
        retention-days: 5
